DEFAULT:
  author: yaxin_zhang
  time: 2020-7-28

ENV:
  n_states: 4
  n_actions: 2
  env_name: CartPole-v1
  max_timesteps: 200

DQN:
  init_epsilon: 0.5
  epsilon_min: 0.01
  epsilon_decay: 0.995
  gamma: 0.9
  alpha: 0.1
  batch_size: 32

  buffer_size: 50000
  learning_rate: 0.001
  tau: 0.95
